name: Lint and test glualint
on: [pull_request, push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: glualint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Nix environment
        run:
          cachix watch-exec glualint -- nix print-dev-env .#ci > "$HOME/.devenv"
      - name: Activate Nix environment
        run: source "$HOME/.devenv"
